services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    network_mode: host
# Use if not using 'network_mode: host'
#    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 443:443/tcp
#      - 3000:3000/tcp
#      - 784:784/udp
#      - 853:853/tcp
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - ./data:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    restart: unless-stopped

