services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    network_mode: host
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ./data:/config # Configuration directory
      - /mnt/movies:/mnt/movies 
      - /mnt/tv:/mnt/tv 
      - /mnt/music:/mnt/music
      - /mnt/movies-c:/mnt/movies-c
      - /mnt/tv-c:/mnt/tv-c
      - /mnt/music-c:/mnt/music-c
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped
    
# For use with Nginx Proxy Manager
# networks:
#   default:
#     external: true
#     name: npmbridge
